const fs = require('fs');
const path = require('path');
const orchestrator = require('./orchestrator_initialization');
const { getNavigationAction: getFormAction } = require('./LLM_FOR_NAVIGATING');
const { getNavigationAction: getBookingAction } = require('./LLM_FOR_BOOKINGS');

/**
 * Invokes the LLM to decide the next action based on:
 * 1. The original query goal.
 * 2. The history of executed steps.
 * 3. The current page accessibility tree.
 * 4. The user's PII memory database (PII.json).
 * 
 * @param {Array} elementsList - The current active page's interactive accessibility elements.
 * @returns {Promise<string>} - The action JSON string generated by the LLM.
 */
async function invokeLLM(elementsList) {
  // 1. Fetch current state from the orchestrator state manager
  const state = orchestrator.getState();
  const query = state.originalTask;
  
  // 2. Fetch the formatted execution history
  const historyStr = orchestrator.getFormattedHistory();

  // 3. Read PII memory dynamically
  const piiPath = path.join(__dirname, 'PII.json');
  let piiData = {};
  try {
    if (fs.existsSync(piiPath)) {
      piiData = JSON.parse(fs.readFileSync(piiPath, 'utf8'));
    }
  } catch (err) {
    console.error('[invokeLLM] Failed to read PII.json:', err.message);
  }

  // 3.5 Check for Human-In-The-Loop OTP or Missing Fields trigger
  const { checkForOtpInput, checkForUnavailableFields } = require('./HumanInTheLoop');
  const otpField = checkForOtpInput(elementsList);
  if (otpField) {
    console.log(`\n[invokeLLM HITL] OTP field detected at index ${otpField.index}: "${otpField.name}". Bypassing LLM query.`);
    const otpPromptAction = JSON.stringify({
      action: "otp_prompt",
      index: otpField.index,
      name: otpField.name
    });
    
    try {
      const logPath = path.join(__dirname, 'llm_debug.log');
      const logContent = `\nTimestamp: ${new Date().toLocaleString()}\nGoal Query: "${query}"\n[HITL Triggered] Bypassed LLM query because OTP field "${otpField.name}" was detected at index ${otpField.index}.\nLLM Response:\n${otpPromptAction}\n--------------------------------------------------\n`;
      fs.appendFileSync(logPath, logContent, 'utf8');
    } catch (err) {}

    return otpPromptAction;
  }

  // 3.6 Check for Human-In-The-Loop Option Selection trigger
  const { checkForOptionSelection } = require('./HumanInTheLoop(Option_Selection)');
  const optionSelectField = checkForOptionSelection(elementsList, state.history);
  if (optionSelectField) {
    console.log(`\n[invokeLLM HITL] Radio option selection detected. Bypassing LLM query.`);
    const optionPromptAction = JSON.stringify({
      action: "option_select_prompt",
      options: optionSelectField.options
    });
    
    try {
      const logPath = path.join(__dirname, 'llm_debug.log');
      const logContent = `\nTimestamp: ${new Date().toLocaleString()}\nGoal Query: "${query}"\n[HITL Triggered] Bypassed LLM query because multiple radio options were detected.\nLLM Response:\n${optionPromptAction}\n--------------------------------------------------\n`;
      fs.appendFileSync(logPath, logContent, 'utf8');
    } catch (err) {}

    return optionPromptAction;
  }

  const missingField = checkForUnavailableFields(elementsList, piiData);
  if (missingField) {
    console.log(`\n[invokeLLM HITL] Missing PII field detected at index ${missingField.index}: "${missingField.name}". Bypassing LLM query.`);
    const humanPromptAction = JSON.stringify({
      action: "human_prompt",
      index: missingField.index,
      name: missingField.name
    });

    try {
      const logPath = path.join(__dirname, 'llm_debug.log');
      const logContent = `\nTimestamp: ${new Date().toLocaleString()}\nGoal Query: "${query}"\n[HITL Triggered] Bypassed LLM query because PII field "${missingField.name}" was missing at index ${missingField.index}.\nLLM Response:\n${humanPromptAction}\n--------------------------------------------------\n`;
      fs.appendFileSync(logPath, logContent, 'utf8');
    } catch (err) {}

    return humanPromptAction;
  }

  console.log('\n=========================================');
  console.log(`[invokeLLM] Invoking LLM for goal: "${query}"`);
  console.log(`[invokeLLM] History:\n${historyStr}`);
  console.log(`[invokeLLM] PII Memory Loaded: ${Object.keys(piiData).join(', ') || 'None'}`);
  console.log('=========================================\n');

  // 4. Query the navigation model
  const { preprocessSelectorMap } = require('./multi_field_filling');
  const cleanedElements = preprocessSelectorMap(elementsList);
  
  // Context-based routing: choose between booking LLM and navigation/form-fill LLM
  const isBookingQuery = /buy|book|purchase|checkout|order|cart|pay/i.test(query);
  
  let actionText;
  if (isBookingQuery) {
    console.log(`[invokeLLM Context Route] 🛒 Booking/Ecommerce query detected. Routing to LLM_FOR_BOOKINGS.js...`);
    actionText = await getBookingAction(query, cleanedElements, historyStr, piiData);
  } else {
    console.log(`[invokeLLM Context Route] 📝 Form filling/Navigation query detected. Routing to LLM_FOR_NAVIGATING.js...`);
    actionText = await getFormAction(query, cleanedElements, historyStr, piiData);
  }
  
  // Post-processing fallback to ensure PII inputs are filled correctly
  let cleanJSONStr = actionText.trim();
  
  // Try extracting code blocks: ```json ... ```
  const jsonBlockRegex = /```json\s*([\s\S]*?)\s*```/g;
  let match;
  let lastBlock = null;
  while ((match = jsonBlockRegex.exec(cleanJSONStr)) !== null) {
    lastBlock = match[1].trim();
  }
  if (!lastBlock) {
    // Fallback: Try general markdown code blocks ``` ... ```
    const codeBlockRegex = /```\s*([\s\S]*?)\s*```/g;
    while ((match = codeBlockRegex.exec(cleanJSONStr)) !== null) {
      lastBlock = match[1].trim();
    }
  }
  
  if (lastBlock) {
    cleanJSONStr = lastBlock;
  } else {
    // Fallback to bracket matching
    const lastActionsIndex = cleanJSONStr.lastIndexOf('"actions"');
    if (lastActionsIndex !== -1) {
      const openBraceIndex = cleanJSONStr.lastIndexOf('{', lastActionsIndex);
      const lastCloseBraceIndex = cleanJSONStr.lastIndexOf('}');
      if (openBraceIndex !== -1 && lastCloseBraceIndex > openBraceIndex) {
        cleanJSONStr = cleanJSONStr.substring(openBraceIndex, lastCloseBraceIndex + 1);
      }
    } else {
      const firstArray = cleanJSONStr.indexOf('[');
      const lastArray = cleanJSONStr.lastIndexOf(']');
      const firstObj = cleanJSONStr.indexOf('{');
      const lastObj = cleanJSONStr.lastIndexOf('}');

      if (firstArray !== -1 && lastArray > firstArray) {
        if (firstObj === -1 || firstArray < firstObj) {
          cleanJSONStr = cleanJSONStr.substring(firstArray, lastArray + 1);
        } else if (firstObj !== -1 && lastObj > firstObj) {
          cleanJSONStr = cleanJSONStr.substring(firstObj, lastObj + 1);
        }
      } else if (firstObj !== -1 && lastObj > firstObj) {
        cleanJSONStr = cleanJSONStr.substring(firstObj, lastObj + 1);
      }
    }
  }

  try {
    const responseObj = JSON.parse(cleanJSONStr);
    let actionsList = [];
    if (responseObj.actions && Array.isArray(responseObj.actions)) {
      actionsList = responseObj.actions;
    } else if (responseObj.action) {
      actionsList = [responseObj];
    }

    let modified = false;
    for (const actionObj of actionsList) {
      if (actionObj.action === 'fill' || actionObj.action === 'select') {
        const targetElement = elementsList.find(el => el.index === actionObj.index);
        if (targetElement) {
          const elName = (targetElement.name || '').toLowerCase();
          const elSelector = (targetElement.selector || '').toLowerCase();
          const elPlayCode = (targetElement.playCode || '').toLowerCase();
          
          const valStr = String(actionObj.value || '');
          const valLower = valStr.toLowerCase();
          const isPlaceholder = valLower.includes('here') || valLower.includes('your_') || valLower === 'but this product' || valLower === 'buy this product' || valLower === '(select card type)' || valLower === 'select card' || valLower === 'select card type';

          const matchesKeyword = (keywords) => {
            return keywords.some(k => elName.includes(k) || elSelector.includes(k) || elPlayCode.includes(k));
          };

          if (matchesKeyword(['phone', 'mobile', 'contact', 'telephone', 'cellphone']) || elName.includes('mobile number or email') || elName.includes('email or mobile') || elSelector.includes('mobile') || elSelector.includes('phone')) {
            const isEmail = valStr.includes('@');
            if (isPlaceholder || isEmail || !/^\d{10,15}$/.test(valStr.replace(/[^0-9]/g, ''))) {
              const phoneVal = piiData.contact?.cell_phone || piiData.contact?.home_phone || piiData.phone_number;
              if (phoneVal) {
                actionObj.value = phoneVal;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced phone/mobile field value with phoneVal: ${phoneVal}`);
              }
            }
          } else if (matchesKeyword(['email', 'mail', 'emailadr'])) {
            const isPhone = /^\d{10,15}$/.test(valStr.replace(/[^0-9]/g, ''));
            const phoneVal = piiData.contact?.cell_phone || piiData.contact?.home_phone || piiData.phone_number;
            if (isBookingQuery && phoneVal) {
              actionObj.value = phoneVal;
              modified = true;
              console.log(`[invokeLLM Path Fallback] Booking route - Preferred phone number over email: ${phoneVal}`);
            } else if ((isPlaceholder || !valStr) && !isPhone) {
              const emailVal = piiData.contact?.email || piiData.email;
              if (emailVal) {
                actionObj.value = emailVal;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced email: ${emailVal}`);
              }
            }
          } else if (matchesKeyword(['username', 'userid', 'user_id', 'user id'])) {
            const isPhone = /^\d{10,15}$/.test(valStr.replace(/[^0-9]/g, ''));
            const phoneVal = piiData.contact?.cell_phone || piiData.contact?.home_phone || piiData.phone_number;
            if (isBookingQuery && phoneVal) {
              actionObj.value = phoneVal;
              modified = true;
              console.log(`[invokeLLM Path Fallback] Booking route - Preferred phone number over username: ${phoneVal}`);
            } else if ((isPlaceholder || !valStr) && !isPhone) {
              const userVal = piiData.contact?.email || piiData.email;
              if (userVal) {
                actionObj.value = userVal;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced username/userid: ${userVal}`);
              }
            }
          } else if (matchesKeyword(['first name', 'firstname', 'frstname'])) {
            if (isPlaceholder || !valStr) {
              if (piiData.first_name) {
                actionObj.value = piiData.first_name;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced first_name: ${piiData.first_name}`);
              }
            }
          } else if (matchesKeyword(['last name', 'lastname'])) {
            if (isPlaceholder || !valStr) {
              if (piiData.last_name) {
                actionObj.value = piiData.last_name;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced last_name: ${piiData.last_name}`);
              }
            }
          } else if (matchesKeyword(['middle name', 'middle initial', 'middle_initial', 'middle_i'])) {
            if (isPlaceholder || !valStr) {
              if (piiData.middle_initial) {
                actionObj.value = piiData.middle_initial;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced middle_initial: ${piiData.middle_initial}`);
              }
            }
          } else if (matchesKeyword(['password', 'pass'])) {
            if (isPlaceholder || !valStr) {
              const passVal = piiData.security?.password;
              if (passVal) {
                actionObj.value = passVal;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced password: ${passVal}`);
              }
            }
          } else if (matchesKeyword(['credit card number', 'card number', 'cc number', 'cardnumber', 'ccnumber'])) {
            if (isPlaceholder || !valStr) {
              const cardNo = piiData.payment?.credit_card_number;
              if (cardNo) {
                actionObj.value = cardNo;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced credit card number`);
              }
            }
          } else if (matchesKeyword(['verification code', 'cvv', 'cvc', 'security code'])) {
            if (isPlaceholder || !valStr) {
              const cvv = piiData.payment?.card_verification_code;
              if (cvv) {
                actionObj.value = cvv;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced CVV/CVC`);
              }
            }
          } else if (matchesKeyword(['cardholder', 'card name', 'card user name', 'cardname', 'name on card', 'cc_uname'])) {
            if (isPlaceholder || !valStr) {
              const cardUser = piiData.payment?.card_user_name;
              if (cardUser) {
                actionObj.value = cardUser;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Cardholder Name: ${cardUser}`);
              }
            }
          } else if (matchesKeyword(['issuing bank', 'bank name', 'card bank', 'ccissuer'])) {
            if (isPlaceholder || !valStr) {
              const bankName = piiData.payment?.card_issuing_bank;
              if (bankName) {
                actionObj.value = bankName;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Issuing Bank: ${bankName}`);
              }
            }
          } else if (matchesKeyword(['customer service phone', 'bank phone', 'service phone', 'cccstsvc'])) {
            if (isPlaceholder || !valStr) {
              const bankPhone = piiData.payment?.card_customer_service_phone;
              if (bankPhone) {
                actionObj.value = bankPhone;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Bank Phone: ${bankPhone}`);
              }
            }
          } else if (matchesKeyword(['sex', 'gender'])) {
            if (isPlaceholder || !valStr) {
              const sex = piiData.personal_details?.sex;
              if (sex) {
                actionObj.value = sex;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Sex/Gender: ${sex}`);
              }
            }
          } else if (matchesKeyword(['social security', 'ssn'])) {
            if (isPlaceholder || !valStr) {
              const ssn = piiData.personal_details?.social_security_number;
              if (ssn) {
                actionObj.value = ssn;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced SSN`);
              }
            }
          } else if (matchesKeyword(['driver license', 'license number', 'driver\'s license', 'driv_lic'])) {
            if (isPlaceholder || !valStr) {
              const dl = piiData.personal_details?.driver_license_number;
              if (dl) {
                actionObj.value = dl;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Driver's License`);
              }
            }
          } else if (matchesKeyword(['age'])) {
            if (isPlaceholder || !valStr) {
              const age = piiData.personal_details?.age;
              if (age) {
                actionObj.value = age;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Age: ${age}`);
              }
            }
          } else if (matchesKeyword(['birth place', 'birthplace', 'place of birth'])) {
            if (isPlaceholder || !valStr) {
              const bp = piiData.personal_details?.birth_place;
              if (bp) {
                actionObj.value = bp;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Birth Place: ${bp}`);
              }
            }
          } else if (matchesKeyword(['income', 'salary'])) {
            if (isPlaceholder || !valStr) {
              const income = piiData.personal_details?.income;
              if (income) {
                actionObj.value = income;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Income: ${income}`);
              }
            }
          } else if (matchesKeyword(['month', 'mm'])) {
            if (isPlaceholder || !valStr) {
              if (matchesKeyword(['exp', 'expiry', 'card'])) {
                const expMonth = piiData.payment?.card_expiration_date?.month;
                if (expMonth) {
                  actionObj.value = expMonth;
                  modified = true;
                  console.log(`[invokeLLM Path Fallback] Replaced Exp Month: ${expMonth}`);
                }
              } else {
                const dobMonth = piiData.personal_details?.date_of_birth?.month;
                if (dobMonth) {
                  actionObj.value = dobMonth;
                  modified = true;
                  console.log(`[invokeLLM Path Fallback] Replaced DOB Month: ${dobMonth}`);
                }
              }
            }
          } else if (matchesKeyword(['year', 'yy'])) {
            if (isPlaceholder || !valStr) {
              if (matchesKeyword(['exp', 'expiry', 'card'])) {
                const expYear = piiData.payment?.card_expiration_date?.year;
                if (expYear) {
                  actionObj.value = expYear;
                  modified = true;
                  console.log(`[invokeLLM Path Fallback] Replaced Exp Year: ${expYear}`);
                }
              } else {
                const dobYear = piiData.personal_details?.date_of_birth?.year;
                if (dobYear) {
                  actionObj.value = dobYear;
                  modified = true;
                  console.log(`[invokeLLM Path Fallback] Replaced DOB Year: ${dobYear}`);
                }
              }
            }
          } else if (matchesKeyword(['day', 'dd', 'date'])) {
            if (isPlaceholder || !valStr) {
              const dobDay = piiData.personal_details?.date_of_birth?.day;
              if (dobDay) {
                actionObj.value = dobDay;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced DOB Day: ${dobDay}`);
              }
            }
          } else if (matchesKeyword(['card type', 'cardtype', 'cc_type'])) {
            if (isPlaceholder || !valStr) {
              const cardType = piiData.payment?.credit_card_type;
              if (cardType) {
                actionObj.value = cardType;
                modified = true;
                console.log(`[invokeLLM Path Fallback] Replaced Card Type: ${cardType}`);
              }
            }
          }
        }
      }
    }
    if (modified) {
      actionText = JSON.stringify(responseObj);
    } else {
      actionText = cleanJSONStr;
    }
  } catch (err) {
    console.error('[invokeLLM Post-Process] Fallback parsing failed:', err.message);
  }
  
  // 5. Log detailed trace to debug file
  try {
    const logPath = path.join(__dirname, 'llm_debug.log');
    const logContent = `
Timestamp: ${new Date().toLocaleString()}
Goal Query: "${query}"
History:
${historyStr}
PII Loaded: ${JSON.stringify(piiData)}
Elements Mapped Count: ${elementsList.length}
LLM Response:
${actionText}
--------------------------------------------------
`;
    fs.appendFileSync(logPath, logContent, 'utf8');
  } catch (err) {
    console.error('[invokeLLM] Failed to write debug log:', err.message);
  }

  return actionText;
}

module.exports = invokeLLM;
